-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 22:52:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `usu_id` INT NOT NULL,
  `usu_cedula` VARCHAR(45) NULL,
  `usu_nombre` VARCHAR(45) NULL,
  `usu_apellido` VARCHAR(45) NULL,
  `usu_edad` INT(2) NULL,
  `usu_sexo` VARCHAR(1) NULL,
  `usu_telefono` VARCHAR(10) NULL,
  `usu_correo` VARCHAR(45) NULL,
  `usu_contrasenia` VARCHAR(45) NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `pac_id` INT NOT NULL,
  `pac_tipo_de_sangre` VARCHAR(45) NULL,
  `pac_historial` VARCHAR(45) NULL,
  `Usuario_usu_id` INT NOT NULL,
  PRIMARY KEY (`pac_id`),
  INDEX `fk_Paciente_Usuario1_idx` (`Usuario_usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Usuario1`
    FOREIGN KEY (`Usuario_usu_id`)
    REFERENCES `mydb`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historias_Clinicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historias_Clinicas` (
  `hc_id` INT NOT NULL,
  `hc_fecha` DATE NULL,
  `observaciones` VARCHAR(45) NULL,
  `Paciente_pac_id` INT NOT NULL,
  PRIMARY KEY (`hc_id`),
  INDEX `fk_Historias_Clinicas_Paciente_idx` (`Paciente_pac_id` ASC) VISIBLE,
  CONSTRAINT `fk_Historias_Clinicas_Paciente`
    FOREIGN KEY (`Paciente_pac_id`)
    REFERENCES `mydb`.`Paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reporte` (
  `r_id` INT NOT NULL,
  `r_datos` VARCHAR(45) NULL,
  `r_balances` DOUBLE NULL,
  `Medico_med_id` INT NOT NULL,
  `Paciente_pac_id` INT NOT NULL,
  PRIMARY KEY (`r_id`),
  INDEX `fk_Reporte_Paciente1_idx` (`Paciente_pac_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reporte_Paciente1`
    FOREIGN KEY (`Paciente_pac_id`)
    REFERENCES `mydb`.`Paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Citas` (
  `ci_id` INT NOT NULL,
  `ci_hora_asiganada` VARCHAR(45) NULL,
  `ci_fecha_asignada` VARCHAR(45) NULL,
  `ci_estado` VARCHAR(45) NULL,
  `Paciente_pac_id` INT NOT NULL,
  PRIMARY KEY (`ci_id`),
  INDEX `fk_Citas_Paciente1_idx` (`Paciente_pac_id` ASC) VISIBLE,
  CONSTRAINT `fk_Citas_Paciente1`
    FOREIGN KEY (`Paciente_pac_id`)
    REFERENCES `mydb`.`Paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicina` (
  `mdc_id` INT NOT NULL,
  `mdc_nombre` VARCHAR(45) NULL,
  `mdc_marca` VARCHAR(45) NULL,
  `mdc_agente_principal` VARCHAR(45) NULL,
  `mdc_fecha_caducidad` VARCHAR(45) NULL,
  `mdc_stock` VARCHAR(45) NULL,
  `mdc_metodo_aplicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`mdc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura_Detalle` (
  `factD_id` INT NOT NULL,
  `factD_pagar_consulta` VARCHAR(45) NULL,
  `factD_pagar_medicina` VARCHAR(45) NULL,
  `factD_pagar_total` VARCHAR(45) NULL,
  `Medicina_mdc_id` INT NOT NULL,
  PRIMARY KEY (`factD_id`),
  INDEX `fk_Factura_Detalle_Medicina1_idx` (`Medicina_mdc_id` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Detalle_Medicina1`
    FOREIGN KEY (`Medicina_mdc_id`)
    REFERENCES `mydb`.`Medicina` (`mdc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta_Contable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta_Contable` (
  `cc_id` INT NOT NULL,
  `cc_nombre` VARCHAR(45) NULL,
  `cc_fecha` DATE NULL,
  `cc_descripcionl` VARCHAR(45) NULL,
  `cc_debe` VARCHAR(45) NULL,
  `cc_haber` VARCHAR(45) NULL,
  `cc_saldo` DOUBLE NULL,
  PRIMARY KEY (`cc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caja` (
  `cj_id` INT NOT NULL,
  `cj_saldo` DOUBLE NULL,
  `Cuenta_Contable_cc_id` INT NOT NULL,
  PRIMARY KEY (`cj_id`),
  INDEX `fk_Caja_Cuenta_Contable1_idx` (`Cuenta_Contable_cc_id` ASC) VISIBLE,
  CONSTRAINT `fk_Caja_Cuenta_Contable1`
    FOREIGN KEY (`Cuenta_Contable_cc_id`)
    REFERENCES `mydb`.`Cuenta_Contable` (`cc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comprobante` (
  `c_id` INT NOT NULL,
  `c_tipo` VARCHAR(45) NULL,
  `c_fecha` DATE NULL,
  `c_numero` INT(5) NULL,
  `Caja_cj_id` INT NOT NULL,
  PRIMARY KEY (`c_id`),
  INDEX `fk_Comprobante_Caja1_idx` (`Caja_cj_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comprobante_Caja1`
    FOREIGN KEY (`Caja_cj_id`)
    REFERENCES `mydb`.`Caja` (`cj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `fact_id` INT NOT NULL,
  `fact_fecha` VARCHAR(45) NULL,
  `Factura_Detalle_factD_id` INT NOT NULL,
  `Comprobante_c_id` INT NOT NULL,
  PRIMARY KEY (`fact_id`),
  INDEX `fk_Factura_Factura_Detalle1_idx` (`Factura_Detalle_factD_id` ASC) VISIBLE,
  INDEX `fk_Factura_Comprobante1_idx` (`Comprobante_c_id` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Factura_Detalle1`
    FOREIGN KEY (`Factura_Detalle_factD_id`)
    REFERENCES `mydb`.`Factura_Detalle` (`factD_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Comprobante1`
    FOREIGN KEY (`Comprobante_c_id`)
    REFERENCES `mydb`.`Comprobante` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta_Medica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta_Medica` (
  `cm_id` INT NOT NULL,
  `cm_fecha` VARCHAR(45) NULL,
  `cm_motivo` VARCHAR(45) NULL,
  `cm_datos_extras` VARCHAR(45) NULL,
  `cm_examenes_requeridos` VARCHAR(45) NULL,
  `Factura_fact_id` INT NOT NULL,
  PRIMARY KEY (`cm_id`),
  INDEX `fk_Consulta_Medica_Factura1_idx` (`Factura_fact_id` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Medica_Factura1`
    FOREIGN KEY (`Factura_fact_id`)
    REFERENCES `mydb`.`Factura` (`fact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificado_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificado_Medico` (
  `cerm_id` INT NOT NULL,
  `cerm_diagnostico` VARCHAR(45) NULL,
  `cer_consideraciones` VARCHAR(45) NULL,
  `Consulta_Medica_cm_id` INT NOT NULL,
  `Paciente_pac_id` INT NOT NULL,
  PRIMARY KEY (`cerm_id`),
  INDEX `fk_Certificado_Medicos_Consulta_Medica1_idx` (`Consulta_Medica_cm_id` ASC) VISIBLE,
  INDEX `fk_Certificado_Medico_Paciente1_idx` (`Paciente_pac_id` ASC) VISIBLE,
  CONSTRAINT `fk_Certificado_Medicos_Consulta_Medica1`
    FOREIGN KEY (`Consulta_Medica_cm_id`)
    REFERENCES `mydb`.`Consulta_Medica` (`cm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Certificado_Medico_Paciente1`
    FOREIGN KEY (`Paciente_pac_id`)
    REFERENCES `mydb`.`Paciente` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sueldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sueldo` (
  `su_id` INT NOT NULL,
  `su_cantidad` VARCHAR(45) NULL,
  `Caja_cj_id` INT NOT NULL,
  `Cuenta_Contable_cc_id` INT NOT NULL,
  PRIMARY KEY (`su_id`),
  INDEX `fk_Sueldo_Caja1_idx` (`Caja_cj_id` ASC) VISIBLE,
  INDEX `fk_Sueldo_Cuenta_Contable1_idx` (`Cuenta_Contable_cc_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sueldo_Caja1`
    FOREIGN KEY (`Caja_cj_id`)
    REFERENCES `mydb`.`Caja` (`cj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sueldo_Cuenta_Contable1`
    FOREIGN KEY (`Cuenta_Contable_cc_id`)
    REFERENCES `mydb`.`Cuenta_Contable` (`cc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colaborador` (
  `colab_id` INT NOT NULL,
  `Usuario_usu_id` INT NOT NULL,
  PRIMARY KEY (`colab_id`),
  INDEX `fk_Colaborador_Usuario1_idx` (`Usuario_usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Colaborador_Usuario1`
    FOREIGN KEY (`Usuario_usu_id`)
    REFERENCES `mydb`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargos` (
  `id_cargo` INT NOT NULL,
  `Sueldo_su_id` INT NOT NULL,
  `Colaborador_colab_id` INT NOT NULL,
  PRIMARY KEY (`id_cargo`),
  INDEX `fk_Cargos_Sueldo1_idx` (`Sueldo_su_id` ASC) VISIBLE,
  INDEX `fk_Cargos_Colaborador1_idx` (`Colaborador_colab_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cargos_Sueldo1`
    FOREIGN KEY (`Sueldo_su_id`)
    REFERENCES `mydb`.`Sueldo` (`su_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargos_Colaborador1`
    FOREIGN KEY (`Colaborador_colab_id`)
    REFERENCES `mydb`.`Colaborador` (`colab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `med_id` INT NOT NULL,
  `Usuario_usu_id` INT NOT NULL,
  PRIMARY KEY (`med_id`),
  INDEX `fk_Medico_Usuario1_idx` (`Usuario_usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Usuario1`
    FOREIGN KEY (`Usuario_usu_id`)
    REFERENCES `mydb`.`Usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especialidad` (
  `es_id` INT NOT NULL,
  `es_especialidad` VARCHAR(45) NULL,
  `Medico_med_id` INT NOT NULL,
  `Sueldo_su_id` INT NOT NULL,
  PRIMARY KEY (`es_id`),
  INDEX `fk_Especialidad_Medico1_idx` (`Medico_med_id` ASC) VISIBLE,
  INDEX `fk_Especialidad_Sueldo1_idx` (`Sueldo_su_id` ASC) VISIBLE,
  CONSTRAINT `fk_Especialidad_Medico1`
    FOREIGN KEY (`Medico_med_id`)
    REFERENCES `mydb`.`Medico` (`med_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especialidad_Sueldo1`
    FOREIGN KEY (`Sueldo_su_id`)
    REFERENCES `mydb`.`Sueldo` (`su_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
